Add field names to types in TypedTree
dotnet/fsharp pull request #10820
Opened 2020-12-30 09:10 UTC by ErikSchierboom

2020-12-30 16:39 UTC, ScottHutchinson requested changes

2020-12-30 16:39 UTC, ScottHutchinson commented on src/fsharp/TypedTree.fs
> +    | TDSwitch of input: Expr * cases: DecisionTreeCase list * defaultCaseOpt: DecisionTree option * range: range
defaultTreeOpt or defaultOpt

2020-12-30 16:39 UTC, ScottHutchinson commented on src/fsharp/TypedTree.fs
> +    | TDSuccess of results: Exprs * targets: int
targetNum or continuationTargetNum

2020-12-31 01:52 UTC, cartermp approved these changes
Thanks!

2020-12-31 01:52 UTC, merged