Add ApplicationIcon/Win32Icon Support
dotnet/fsharp pull request #11310
Opened 2021-03-26 06:51 UTC by albert-du

fix for #10065
Currently the `<ApplicationIcon>` property group and `win32icon` compiler option aren't working for f# but are for c#/vb. _`<ApplicationIcon>` is already defined as a property group but doesn't do anything_. `win32icon` is added in the tooltask and compiler options. The icon's attached as a native resource in `\src\fsharp\CreateILModule.fs` using the same logic as Roslyn, ignoring if it doesn't exist, a win32res file is specified, or the output type is set to a dll. Actually conversion of the icon file to resource bytes is handled by existing code in `\src\fsharp\absil\ilnativeres.fs`

* adds compiler flag `--win32icon`
* adds fixes property group `<ApplicationIcon>`
* adds "win32icon" compiler option, a path to an `.ico` file 
    * included as a native resource
    * ignored when output type is set to dll
    * ignored when win32res is included

2021-03-26 06:51 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=11310) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=11310) before we can accept your contribution.<br/><br/>:x: albert-du [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=11310)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=11310) it.</sub>

2021-03-27 14:41 UTC, cartermp requested changes
Thanks, I think this looks great! One tiny code change.

2021-03-27 14:41 UTC, cartermp commented on src/fsharp/CreateILModule.fs
> +                  let ms = new MemoryStream()
```suggestion
                  use ms = new MemoryStream()
```

2021-03-27 17:44 UTC, albert-du commented
Cool, thanks for looking at it

2021-03-29 00:32 UTC, KevinRansom approved these changes
Thanks for taking care of this.

2021-03-29 00:56 UTC, cartermp approved these changes

2021-03-29 00:56 UTC, merged

2021-04-02 05:24 UTC, albert-du commented
@cartermp 
It seems that error occurs when there's a discrepancy between the msbuild [.targets](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets) fiile and the built Fsc [tooltask](https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Build/Fsc.fs). Rebuilding the compiler and FSharp.Build should fix it.
https://github.com/dotnet/fsharp/blob/f7a55c0b102a2e5c2aaaaa2373c4ae8b8809621f/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L332
*when this line exists, but the ToolTask hasn't been rebuild, it's unusable*

2021-04-02 16:43 UTC, cartermp commented
Gotcha, makes sense. I don't think I rebuilt the proto compiler when doing builds. Disregard, and thanks!