bump FCS version to 40.0.0 for nightly prereleases
dotnet/fsharp pull request #11380
Opened 2021-04-05 01:49 UTC by baronfel

This closes #11285 by bumping the version number in the `main` branch for FCS builds to 40.0.0. This merely reflects the reality of things now (as changes intended for 40.x are already included in `main` and the matching changelogs are in place), and makes it easier on devs consuming the prerelease nightly feeds to have a version that semantically meaningful.

Right now nightly build versions are using the version base of 39.0.0, which means that current users of 39.0.3 stable cannot upgrade meaningfully/simply in their tool of choice.

2021-04-05 20:23 UTC, baronfel commented
So the failures all look like infrastructure/CI failures :-/ Not sure there's anything I can do with that.

2021-04-06 03:07 UTC, KevinRansom requested changes
Please ... no ... version numbers are stupid enough as they are.

The next release of fcs, comes from either release/fcs ... if it's a minor release or release/Dev16.10 if it's a major release.

Regardless, once that happens all changes will be ri'd back to main  ... although ideally, they will have originated in main.

If you want to build with a different number on your machine, edit the file locally, otherwise.   Or build with release/Dev16.10

2021-04-06 03:21 UTC, baronfel commented
So @KevinRansom right now my contention then is that nightly builds of FCS are effectively broken then, as they're publishing with versions of 39.0.0 prerelease which isn't usable not discoverable to someone using a nuget/paket client. I think that the 40 version (which we already know will be the next version, from the changelogs in this repo already) should come from master and be merged into whatever release branch y'all deem fit, but we on the outside can't consume prerelease packages to prepare for that, which means we're disadvantaged compare to all y'all with your in-tree builds.

I'm just looking for the minimal way to get nightlies correct again.

2021-04-06 16:12 UTC, baronfel commented
Maybe the tack that we should take here is to identify _why_ the nightlies are stamping the wrong version numbers and address that? I confess that I have zero idea how exactly that stamping happens, e.g. I don't see a nightly FCS build in the azdo yaml for example. Is there any visibility/insight into that process?

2021-04-08 19:18 UTC, KevinRansom commented
@baronfel, A couple of things.
1:  The FCS nuget package is a product of our build, it is never an input.
2:  When we inject the FCS package into other products ... we "almost always" take it from the next preview branch currently release/Dev16.10.  we never take it from branch **main**.
3:  To get the bits that will be shipped next time, the only reliable spot is release/Dev16.10
4:  We prop nightly packages to a feed that is publicly available, so updating main to 40.0.0 will cause confusion because that feed would contain 40.0.0 from two different branches, built with different sets of source code.

What is the specific issues with nightlies you are trying to address?  and what do you mean by nightlies?

2021-04-08 20:06 UTC, baronfel commented
Thanks for the details!

By 'nightlies' I refer to the nightly-built versions of FCS that are pushed to the internal feed `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`. FSAC uses this feed in order to preview and pre-emptively adjust to API changes and do tests of how new FCS changes would integrate into our LSP solution.

For a while now (at least since the beginning of March) the version of these nightly packages hasn't advanced past version `39.0.3-preview.21102.10`.  This seems to be primarily because the nightly versions began pushing on an even earlier version after that (currently the most recently-built package I can find on the feed is version `39.0.0-preview.21206.1`).

This version reversion makes it very hard to test upgrades/new features because the version numbers on the packages go down, which means various package bounds are now incorrect. In addition, it's hard to test new features because the prerelease is thought of as 'less' than the current stable release.

So my request is that wherever the nightlies (and eventually the stable FCS package) are being built out out of, that location starts publishing 40.0.0 prereleases because:
* we know there are API breakages (on purposes, so the next major version should be advanced)
* prerelease because the package hasn't been officially stamped yet
* and ideally, this sort of version incrementing would be done (not necessarily only by Microsoft, but by any interested contributor) soon/immediately with the release of the stable package.

2021-04-08 20:16 UTC, KevinRansom commented
Aha!!! Completely to my surprise ...
the release/Dev10.0 branch hasn't been updated to 40.0.0,  Indeed it hadn't even made it to 39.0.3.  I will cherry pick your change and merge it to release/dev16.10.  I was convinced it had been .... Too many moving parts I guess.

Thanks

Kevin

From: Chet Husk ***@***.***>
Sent: Thursday, April 8, 2021 1:07 PM
To: dotnet/fsharp ***@***.***>
Cc: Kevin Ransom ***@***.***>; Mention ***@***.***>
Subject: Re: [dotnet/fsharp] bump FCS version to 40.0.0 for nightly prereleases (#11380)


Thanks for the details!

By 'nightlies' I refer to the nightly-built versions of FCS that are pushed to the internal feed https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json. FSAC uses this feed in order to preview and pre-emptively adjust to API changes and do tests of how new FCS changes would integrate into our LSP solution.

For a while now (at least since the beginning of March) the version of these nightly packages hasn't advanced past version 39.0.3-preview.21102.10. This seems to be primarily because the nightly versions began pushing on an even earlier version after that (currently the most recently-built package I can find on the feed is version 39.0.0-preview.21206.1).

This version reversion makes it very hard to test upgrades/new features because the version numbers on the packages go down, which means various package bounds are now incorrect. In addition, it's hard to test new features because the prerelease is thought of as 'less' than the current stable release.

So my request is that wherever the nightlies (and eventually the stable FCS package) are being built out out of, that location starts publishing 40.0.0 prereleases because:

  *   we know there are API breakages (on purposes, so the next major version should be advanced)
  *   prerelease because the package hasn't been officially stamped yet
  *   and ideally, this sort of version incrementing would be done (not necessarily only by Microsoft, but by any interested contributor) soon/immediately with the release of the stable package.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Ffsharp%2Fpull%2F11380%23issuecomment-816135965&data=04%7C01%7CKevin.Ransom%40microsoft.com%7Cc5825689d5224c9741aa08d8fac9d5fc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535092078410031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FM8zIaX%2Bc0Gr%2Bzxa3WSM6erqDTwP5bwcyxzcllcWy30%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABHPUFX5PNGDCXF3HYOUIRDTHYEFLANCNFSM42MAQZEA&data=04%7C01%7CKevin.Ransom%40microsoft.com%7Cc5825689d5224c9741aa08d8fac9d5fc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535092078415014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WEsTIHRszknMRwc36wmwA20nVY8wVoxir81yD9dCNOY%3D&reserved=0>.

2021-04-08 20:58 UTC, KevinRansom commented
@baronfel, yes.

2021-04-08 21:01 UTC, KevinRansom commented
This will be managed here:  https://github.com/dotnet/fsharp/pull/11393

2021-04-10 03:08 UTC, KevinRansom commented
merged here: https://github.com/dotnet/fsharp/pull/11393

2021-04-10 03:08 UTC, closed without merging