Optimize interpolated string with no holes
dotnet/fsharp pull request #11632
Opened 2021-06-04 10:49 UTC by kerams

```fsharp
let stringOnly () = $"no hole" 
let printed () = printf $"printed no hole"
```

becomes

```csharp
public static string stringOnly()
{
    return "no hole";
}

public static void printed()
{
    PrintfFormat<Unit, TextWriter, Unit, Unit> format = new PrintfFormat<Unit, TextWriter, Unit, Unit, Unit>("printed no hole");
    PrintfModule.PrintFormatToTextWriter(Console.Out, format);
}
```

instead of

```csharp
public static string stringOnly()
{
    return PrintfModule.PrintFormatToStringThen(new PrintfFormat<string, Unit, string, string, Unit>("no hole", new object[0], null));
}

public static void printed()
{
    PrintfFormat<Unit, TextWriter, Unit, Unit> format = new PrintfFormat<Unit, TextWriter, Unit, Unit, Unit>("printed no hole", new object[0], null);
    PrintfModule.PrintFormatToTextWriter(Console.Out, format);
}
```

2021-06-04 12:58 UTC, kerams commented
If I were to create a replaced of `sprintf "xxx"` with `"xxx"`, where would be the place to do it? I don't see how in CheckExpressions, so then I considered `OptimizeApplication`, checking for `sprintf` and 'constant' format, but it seems incredibly specific compared to the what the function does.

2021-06-04 22:18 UTC, charlesroddie commented
`$"no hole"` is terrible code, even if there are workarounds put in to make it perform well. An analyzer is the correct solution isn't it?

2021-06-05 06:14 UTC, kerams commented
Yes, it's pointless and no one sets out to write that initially, but I can imagine a scenario where there was actual interpolation, then someone removed it, but forgot the `$`. The same with `sprintf "xxx"`, perhaps less likely.

2021-06-05 07:03 UTC, charlesroddie commented
Yes, and the right solution is to help fix the code (using analyzers) rather than work around it. Isn't it?

2021-06-05 07:26 UTC, kerams commented
I'd say a compiler/analyzer warning would be complementary, and concerned with code style rather than performance. There's no reason we should emit suboptimal code if the user does not notice or heed the warning (when it's this easy to fix, to be precise). If you consider this one extra character a crime against humanity, by all means go ahead and also implement an analyzer. I'm not fussed myself.

2021-06-05 15:26 UTC, cartermp commented
I think this is a fine addition. We're not in the business of punishing people for writing what someone might personally find to be bad code.

2021-06-29 11:41 UTC, dsyme commented
> We're not in the business of punishing people for writing what someone might personally find to be bad code.

:) `let mutable x = ...`  🤣

2021-06-29 11:42 UTC, dsyme commented on src/fsharp/CheckExpressions.fs
> +            let str = mkString g m printfFormatString
In theory this changes the quotation form for an interpolated string.  I don't mind that change, however could you add a test in `tests/fsharp/core/quotes/test.fsx` or elsewhere to test for that and pin down the new form please?

e.g. check results of `<@ $"abc" @>`  and you may as well add a test for `<@ $"abc {1} def" @>` while you're at it.

2021-06-29 11:43 UTC, dsyme requested changes
Approved, just add a test for quotation forms please

2021-06-29 12:01 UTC, kerams commented
Done. Will the test run automatically or do I need to wire it up somewhere?

2021-06-29 14:23 UTC, dsyme commented
> Done. Will the test run automatically or do I need to wire it up somewhere?


All of the initialization code of quotes/test.fsx runs automatically as one test

2021-06-29 14:23 UTC, dsyme approved these changes
Approved, subject to green ticks

2021-06-29 15:47 UTC, merged