Added examples for Async.WebExtensions
dotnet/fsharp pull request #12644
Opened 2022-01-26 02:31 UTC by leolorenzoluis

Not sure if it's worth adding examples here because `WebClient` is deprecated in favor of `HttpClient` but I did it anyway. 
Please see FSharp.Control.Async.WebExtensions https://github.com/dotnet/fsharp/issues/12124

2022-01-26 02:31 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12644) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12644) before we can accept your contribution.<br/><br/>:x: leolorenzoluis [sign now](https://cla.dotnetfoundation.org/dotnet/fsharp?pullRequest=12644)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/fsharp?pullRequest=12644) it.</sub>

2022-01-26 20:27 UTC, dsyme commented on src/fsharp/FSharp.Core/async.fsi
> +            /// let responseStreamToString = fun (responseStream : System.Net.WebResponse) ->
You can add `open System` and `open System.IO` and `open System.Net` at the top of the sample I think.  Best to keep the code crisp.

2022-01-26 20:28 UTC, dsyme commented on src/fsharp/FSharp.Core/async.fsi
> +            /// System.Uri("https://www.microsoft.com") |> client.AsyncDownloadString |> Async.RunSynchronously
Change to a more neutral URL like https://www.w3.org/

2022-01-26 20:28 UTC, dsyme commented on src/fsharp/FSharp.Core/async.fsi
> +            /// client.AsyncDownloadData(Uri("https://www.microsoft.com")) |> Async.RunSynchronously |> System.Text.Encoding.ASCII.GetString
Likewise here, use https://www.w3.org/

2022-01-26 20:28 UTC, dsyme commented on src/fsharp/FSharp.Core/async.fsi
> +            /// System.Uri("https://www.microsoft.com") |> fun x -> client.AsyncDownloadFile(x, "output.html") |> Async.RunSynchronouslyl
Likewise here, use https://www.w3.org/

2022-01-26 20:28 UTC, dsyme requested changes
Looks great, just a few small changes requested

2022-01-27 01:41 UTC, leolorenzoluis commented
@dsyme - Thank you for reviewing. I've updated the files.

2022-01-27 16:05 UTC, merged