fix delegate name resolution
dotnet/fsharp pull request #12939
Opened 2022-04-04 15:13 UTC by dsyme

This fixes https://github.com/dotnet/fsharp/issues/10228

It implements the fix as a language feature initially in preview

* In theory it can change name resolution for some existing code - a delegate type would have to shadow an existing type of the same name that has accessible constructors, and code would actually have to make use of this. 
* However this will be exceedingly rare

The problem is certainly a bug and I think it could have been addressed as such and so using a language feature is just being conservative in case someone needs to unapply this fix.

@KevinRansom @vzarytovskii Please  check if you agree with this resolution.

2022-04-05 01:32 UTC, KevinRansom commented
@dsyme, make the language feature an F# 6.0 version feature rather than a preview feature. 

We won't be revving the language version for a while yet.  This can be thought of as a bug in F# 6.0, which they would have had to fix in the move to F# 6.0 any way.

2022-04-05 01:33 UTC, KevinRansom approved these changes
Other than making it not a preview fix.  Looks good.

2022-04-05 01:35 UTC, KevinRansom requested changes
Make it a 6.0 language version rather than a preview feature.

2022-04-06 01:33 UTC, dsyme commented
> Make it a 6.0 language version rather than a preview feature.

OK. Makes sense, thanks

2022-04-06 01:35 UTC, dsyme commented
Done.

2022-04-06 05:12 UTC, KevinRansom approved these changes
Thanks

2022-04-06 06:21 UTC, merged