Optimize integer for loop code gen
dotnet/fsharp pull request #13573
Opened 2022-07-26 23:41 UTC by albert-du

#938 #9548

Optimizes `for i in n .. step .. m do` il code gen to avoid allocation.

Throws ArgumentException at runtime if step is zero.

Replicates logic of OperatorIntrinsics.RangeInt32 with additional optimizations if the step is a non-zero compiled constant.

Example: 
```fsharp
let f n step m =
    for i in n..step..m do
        System.Console.WriteLine()
```
Before:
```cil
.method public static 
    void f (
        int32 n,
        int32 step,
        int32 m
    ) cil managed 
{
    .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationArgumentCountsAttribute::.ctor(int32[]) = (
        01 00 03 00 00 00 01 00 00 00 01 00 00 00 01 00
        00 00 00 00
    )
    // Method begins at RVA 0x2050
    // Code size 59 (0x3b)
    .maxstack 5
    .locals init (
        [0] class [System.Runtime]System.Collections.Generic.IEnumerable`1<int32>,
        [1] class [System.Runtime]System.Collections.Generic.IEnumerator`1<int32>,
        [2] int32,
        [3] class [System.Runtime]System.IDisposable
    )

    IL_0000: ldarg.0
    IL_0001: ldarg.1
    IL_0002: ldarg.2
    IL_0003: call class [System.Runtime]System.Collections.Generic.IEnumerable`1<int32> [FSharp.Core]Microsoft.FSharp.Core.Operators/OperatorIntrinsics::RangeInt32(int32, int32, int32)
    IL_0008: stloc.0
    IL_0009: ldloc.0
    IL_000a: callvirt instance class [System.Runtime]System.Collections.Generic.IEnumerator`1<!0> class [System.Runtime]System.Collections.Generic.IEnumerable`1<int32>::GetEnumerator()
    IL_000f: stloc.1
    .try
    {
        // loop start (head: IL_0010)
            IL_0010: ldloc.1
            IL_0011: callvirt instance bool [System.Runtime]System.Collections.IEnumerator::MoveNext()
            IL_0016: brfalse.s IL_0026

            IL_0018: ldloc.1
            IL_0019: callvirt instance !0 class [System.Runtime]System.Collections.Generic.IEnumerator`1<int32>::get_Current()
            IL_001e: stloc.2
            IL_001f: call void [System.Console]System.Console::WriteLine()
            IL_0024: br.s IL_0010
        // end loop

        IL_0026: leave.s IL_003a
    } // end .try
    finally
    {
        IL_0028: ldloc.1
        IL_0029: isinst [System.Runtime]System.IDisposable
        IL_002e: stloc.3
        IL_002f: ldloc.3
        IL_0030: brfalse.s IL_0039

        IL_0032: ldloc.3
        IL_0033: callvirt instance void [System.Runtime]System.IDisposable::Dispose()
        IL_0038: endfinally

        IL_0039: endfinally
    } // end handler

    IL_003a: ret
} // end of method _::f
```
```csharp
public static void f(int n, int step, int m)
{
    IEnumerable<int> enumerable = Operators.OperatorIntrinsics.RangeInt32(n, step, m);
    IEnumerator<int> enumerator = enumerable.GetEnumerator();
    try
    {
        while (enumerator.MoveNext())
        {
            int current = enumerator.Current;
            Console.WriteLine();
        }
    }
    finally
    {
        IDisposable disposable = enumerator as IDisposable;
        if (disposable != null)
        {
            disposable.Dispose();
        }
    }
}
```
After:
```cil
.method public static void  f(int32 n,
                              int32 step,
                              int32 m) cil managed
{
  .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationArgumentCountsAttribute::.ctor(int32[]) = ( 01 00 03 00 00 00 01 00 00 00 01 00 00 00 01 00 
                                                                                                                  00 00 00 00 ) 
  // Code size       67 (0x43)
  .maxstack  4
  .locals init (int32 V_0,
           int32 V_1,
           int32 V_2)
  IL_0000:  ldarg.0
  IL_0001:  stloc.2
  IL_0002:  ldarg.1
  IL_0003:  stloc.1
  IL_0004:  ldloc.1
  IL_0005:  brtrue.s   IL_0017

  IL_0007:  ldstr      "The step of a range cannot be zero."
  IL_000c:  ldstr      "step"
  IL_0011:  newobj     instance void [mscorlib]System.ArgumentException::.ctor(string,
                                                                               string)
  IL_0016:  throw

  IL_0017:  ldarg.2
  IL_0018:  stloc.0
  IL_0019:  ldloc.0
  IL_001a:  ldloc.2
  IL_001b:  blt.s      IL_0021

  IL_001d:  ldloc.1
  IL_001e:  ldc.i4.0
  IL_001f:  bgt.s      IL_0029

  IL_0021:  ldloc.0
  IL_0022:  ldloc.2
  IL_0023:  bgt.s      IL_0042

  IL_0025:  ldloc.1
  IL_0026:  ldc.i4.0
  IL_0027:  bge.s      IL_0042

  IL_0029:  call       void [mscorlib]System.Console::WriteLine()
  IL_002e:  ldloc.2
  IL_002f:  ldloc.1
  IL_0030:  add
  IL_0031:  stloc.2
  IL_0032:  ldloc.2
  IL_0033:  ldloc.0
  IL_0034:  ble.s      IL_003a

  IL_0036:  ldloc.1
  IL_0037:  ldc.i4.0
  IL_0038:  bgt.s      IL_0042

  IL_003a:  ldloc.2
  IL_003b:  ldloc.0
  IL_003c:  bge.s      IL_0029

  IL_003e:  ldloc.1
  IL_003f:  ldc.i4.0
  IL_0040:  bge.s      IL_0029

  IL_0042:  ret
} // end of method Test::f
```
```csharp
public static void f(int n, int step, int m)
{
    int num = n;
    if (step == 0)
    {
        throw new ArgumentException("The step of a range cannot be zero.", "step");
    }
    if ((m < num || step <= 0) && (m > num || step >= 0))
    {
        return;
    }
    while (true)
    {
        Console.WriteLine();
        num += step;
        if ((num > m && step > 0) || (num < m && step < 0))
        {
            break;
        }
    }
}
```

Constant step optimization:
```fsharp
let f n m =
    for i in n..2..m do
        System.Console.WriteLine()
```

```cil
.method public static void  f(int32 n,
                              int32 m) cil managed
{
    .custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationArgumentCountsAttribute::.ctor(int32[]) = ( 01 00 02 00 00 00 01 00 00 00 01 00 00 00 00 00 ) 
    // Code size       22 (0x16)
    .maxstack  4
    .locals init (int32 V_0,
                  int32 V_1)
    IL_0000:  ldarg.0
    IL_0001:  stloc.1
    IL_0002:  ldarg.1
    IL_0003:  stloc.0
    IL_0004:  ldloc.0
    IL_0005:  ldloc.1
    IL_0006:  blt.s      IL_0015
    IL_0008:  call       void [mscorlib]System.Console::WriteLine()
    IL_000d:  ldloc.1
    IL_000e:  ldc.i4.2
    IL_000f:  add
    IL_0010:  stloc.1
    IL_0011:  ldloc.1
    IL_0012:  ldloc.0
    IL_0013:  ble.s      IL_0008
    IL_0015:  ret
} // end of method Test::f
```

```csharp
public static void f(int n, int m)
{
    int num = n;
    if (m < num)
    {
        return;
    }
    while (true)
    {
        Console.WriteLine();
        num += 2;
        if (num > m)
        {
            break;
        }
    }
}
```

2022-07-27 09:49 UTC, vzarytovskii commented
Nice. Can I please ask you to add some benchmarks, so we understand what are implications in runtime here?

Comparisons - before/after, comparison with normal loop, etc.

Also: 
> Throws ArgumentException at runtime if step is zero.

What is current behaviour? Also, it should produce warning/error if step is constant and known at compile time.

2022-07-28 06:22 UTC, albert-du commented
@vzarytovskii I added benchmark results to the original pr message. 

Throwing an error at runtime is a behavior replicated from the [RangeInt32](https://github.com/dotnet/fsharp/blob/9f971c8ca85a3bcc0006f15db01d8e19a58592d7/src/FSharp.Core/prim-types.fs#L5701) enumerator type that backed the .. .. syntax. [sharplab example](https://sharplab.io/#v2:DYLgZgzgNALiBOBXAdlAJiA1AHwPS4AIBjAewFsAHAS2AFMICAjRGAtE+5AclaWQFgAUGBLwCVccgIBGAgDo5BAAzzF0lewJCCOghXhVkMMFIBEpoA==) I can look into displaying a warning/error if the step is zero however it might be better to emit such a message for any usage of an integer range step not just in a for loop.

2022-07-28 16:47 UTC, vzarytovskii commented
> @vzarytovskii I added benchmark results to the original pr message.
> 
Thanks!

> Throwing an error at runtime is a behavior replicated from the [RangeInt32](https://github.com/dotnet/fsharp/blob/9f971c8ca85a3bcc0006f15db01d8e19a58592d7/src/FSharp.Core/prim-types.fs#L5701) enumerator type that backed the .. .. syntax. [sharplab example](https://sharplab.io/#v2:DYLgZgzgNALiBOBXAdlAJiA1AHwPS4AIBjAewFsAHAS2AFMICAjRGAtE+5AclaWQFgAUGBLwCVccgIBGAgDo5BAAzzF0lewJCCOghXhVkMMFIBEpoA==) I can look into displaying a warning/error if the step is zero however it might be better to emit such a message for any usage of an integer range step not just in a for loop.

Yep, agree, should be done separately for all such cases.

2022-07-28 23:52 UTC, albert-du commented
I've made further improvements to the codegen that results in smaller and faster il

2022-07-29 16:50 UTC, albert-du commented
this is ready

2022-08-03 23:46 UTC, abelbraaksma commented
> 79.8% faster, while smaller and without allocation.

Wow! I noticed you showed timings for a loop of 90x, did you see similar behavior with larger loops? Did you compare when there is slightly more code in the body, or some reference type so that JIT cannot optimize everything away? Just curious! These timings are amazing!

2022-08-08 18:51 UTC, vzarytovskii approved these changes
This LGTM, need one more approval @KevinRansom @dsyme @0101 @psfinaki

2022-08-17 10:28 UTC, dsyme commented
@albert-du This is fantastic work

We need some more testing

* We have to test loops near Int32.MaxValue.  These can be really difficult to get right since adding the step causes the value to wrap around.  It's quite possible what you have will have problems for these loops - this is tha major reason why we haven't optimized more loops previously.

* We have to test tasks containing these loops, since you've made changes in the resumable code state machines.

* Please make additions to `tests\walkthroughs\DebugStepping\TheBigFileOfDebugStepping.fsx`, then compile that file (add a project file to that directory if you like and add it to the solution) and test the stepping and breakpoints for these loops

2022-08-17 10:29 UTC, dsyme requested changes
See comments above

2022-08-22 20:29 UTC, albert-du commented
@dsyme I added over/underflow checking to the constant step optimized loops, variable step loops don't seem to suffer from this as the logic was completely lifted from RangeInt32. Tests for under/overflow checking and tasks added. Debug stepping for loops looks good.

2022-08-23 05:12 UTC, albert-du commented
benchmarks updated

2022-08-23 14:27 UTC, dsyme requested changes
Some further changes are going to be needed here to move the optimization out of checking and into Optimizer.fs or similar, to avoid additions to the quotation API and changes to quotation formats.

This is a little painful as the loop lowering code is placed most naturally in CheckExpressions.

Do you feel able to try the changes with guidance?  I'd be happy to help you with them

2022-08-23 14:27 UTC, dsyme commented on src/Compiler/Checking/QuotationTranslator.fs
> +        | TOp.IntegerForLoop (_, _, _), [], [Expr.Lambda (_, _, _, [_], lim0, _, _);Expr.Lambda (_, _, _, [_], lim1, _, _);body; Expr.Lambda (_, _, _, [_], step, _, _)] ->
I'm concerned by the addition of these new quotation constructs, see above

2022-08-23 14:27 UTC, dsyme commented on src/FSharp.Core/quotations.fsi
> +    val (|ForIntegerRangeLoopWithStep|_|): input: Expr -> (Var * Expr * Expr * Expr * Expr) option
Optimizations shouldn't really cause additions to the quotation API.  If we were to add something, we would need to add a corresponding quotation construction method, e.g. similar to https://github.com/dotnet/fsharp/blob/9978a14a48812b18f0c5b3caa33602df8749fe78/src/FSharp.Core/quotations.fs#L2632

2022-08-23 14:27 UTC, dsyme commented on src/Compiler/Checking/CheckExpressions.fs
> +            when valRefEq g vref g.range_step_op_vref && typeEquiv g tyarg g.int_ty && typeEquiv g stepTyarg g.int_ty ->
I think we may need to guard this via a language version switch or move this to an optimization phase (though that is painful).  It changes the form of quotations for these constructs which is a breaking change.

Quoting these loops is rare but it's also more philosophical: we shouldn't be adding any optimizations which change the quoted form or require new additions to the quotations API.  So optimziations should be in later phases.

2022-08-24 03:43 UTC, albert-du commented
@dsyme I think I'd like to try making those changes, it'll be a good opportunity for me to understand more of the compiler

2022-12-28 14:26 UTC, charlesroddie commented
That's 400% to 1740% faster!

2022-12-29 01:04 UTC, abelbraaksma commented
@albert-du please don’t let this go stale, it’s amazing work! 💯  If it gets behind ‘main’ for too long, the conflicts may become hard to solve. If you need some help with seeing this through, feel free to ping me, or anybody, on F# Slack.

2022-12-30 02:45 UTC, albert-du commented
@abelbraaksma I've been busy with school the past few months but I fully intend to work more on this soon. Thank you so much for your support!

2024-05-16 13:57 UTC, psfinaki commented
This was subsumed by @brianrourkeboll in [his PR](https://github.com/dotnet/fsharp/pull/16650), closing this one.

2024-05-16 13:57 UTC, closed without merging