Streamlining some dependencies around Microsoft.CodeAnalysis
dotnet/fsharp pull request #13637
Opened 2022-08-05 11:59 UTC by psfinaki

I've noticed some weird behavior in some of the test files. The project compiles, but some files show errors:
![image](https://user-images.githubusercontent.com/5451366/183071776-ff45bdb1-1127-42d4-ba7c-2e61b11449c4.png)

We briefly discussed this with @KevinRansom, looks like we have code in FSharp.PatternMatcher which effectively duplicates what's already there in Microsoft.CodeAnalysis. So we can remove that and simplify things a bit.

Moreover, turned out we have dependencies on some auxiliary packages which are [not meant](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Workspaces.Common/4.3.0-3.final#readme-body-tab) for direct usage:
![image](https://user-images.githubusercontent.com/5451366/183072276-f2b1d5d1-68af-4f2f-8e81-764865b7b34e.png)

This is also fixed here.

2022-08-05 12:22 UTC, vzarytovskii requested changes
Please make sure explicitly that vsix is deployable to roslyndev  and everything works in 17.4 (colouring, intellisense, autoformatting, and everything which is tied to workspaces and editor features).

The guide is in DEVGUIDE.md.

2022-08-05 12:22 UTC, vzarytovskii commented
Also, please retarget PR to 17.4 branch.

2022-08-05 13:58 UTC, psfinaki commented
/azp run

2022-08-05 17:45 UTC, KevinRansom approved these changes

2022-08-09 18:40 UTC, vzarytovskii approved these changes

2022-08-09 18:40 UTC, merged