Consolidating code around process exiting
dotnet/fsharp pull request #13784
Opened 2022-08-25 12:00 UTC by psfinaki

closes #13748 

So apparently we already have the right thing in the codebase so just plugging it in in a couple places.

2022-08-29 12:08 UTC, 0101 approved these changes

2022-08-29 22:52 UTC, KevinRansom requested changes
I think we should consider parameterizing the process exiter.

2022-09-15 13:40 UTC, KevinRansom commented on src/Compiler/Driver/ParseAndCheckInputs.fs
> +        tcConfigB: TcConfigBuilder,
probably not this.

2022-09-15 16:23 UTC, KevinRansom approved these changes
Nice.

Thank you

2022-09-15 17:11 UTC, vzarytovskii approved these changes

2022-09-16 08:28 UTC, psfinaki commented
/azp run

2022-09-17 00:00 UTC, merged