Refactoring langversion options in FSC
dotnet/fsharp pull request #13785
Opened 2022-08-25 15:31 UTC by psfinaki

closes #13749

Splitting the all-in-one flag into two clear options, similar to how we have it with some other things like `target` or `debug`.

2022-08-29 11:53 UTC, 0101 commented on src/Compiler/Driver/CompilerOptions.fs
> +    sb.ToString()
How about
```fsharp
seq { 
    FSComp.SR.optsSupportedLangVersions ()
    yield! LanguageVersion.Default.ValidOptions
    yield! LanguageVersion.Default.ValidVersions
} |> String.concat "\n"

2022-08-29 11:55 UTC, 0101 approved these changes

2022-09-02 22:34 UTC, KevinRansom requested changes
We should talk

2022-09-09 14:38 UTC, psfinaki commented on src/Compiler/Driver/CompilerOptions.fs
> +    sb.ToString()
Yep, good idea, changed

2022-09-09 14:39 UTC, psfinaki commented on src/Compiler/Driver/CompilerOptions.fs
> +    for v in LanguageVersion.Default.ValidVersions do
Rebased on that

2022-09-09 14:39 UTC, psfinaki commented on src/Compiler/Driver/CompilerOptions.fs
> +                QuitProcessExiter.Exit 0),
Returned exit 0 for now

2022-09-09 14:39 UTC, psfinaki commented on src/Compiler/Driver/CompilerOptions.fsi
> +val GetLanguageVersions: unit -> string
For testing

2022-09-12 12:33 UTC, closed without merging