Update public pool names
dotnet/fsharp pull request #13820
Opened 2022-09-01 01:52 UTC by alexperovich

This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.

2022-09-01 09:35 UTC, vzarytovskii approved these changes

2022-09-01 09:36 UTC, vzarytovskii commented
/azp run

2022-09-01 21:51 UTC, KevinRansom requested changes
Will delete when code flow complete

2022-09-02 10:09 UTC, vzarytovskii commented
Change in 17.4 already, closing this one

2022-09-02 10:09 UTC, closed without merging