Cherry pick  #13987 to 17.4
dotnet/fsharp pull request #13988
Opened 2022-09-26 23:20 UTC by dsyme

See #13987

2022-09-26 23:20 UTC, dsyme commented
@vzarytovskii please approve when you can

2022-09-27 07:29 UTC, T-Gro approved these changes

2022-09-27 07:30 UTC, T-Gro commented
AssemblyVersion03.fs test failed, but I believe it is because of its time sensitivity. Rerunning checks.

2022-09-27 08:06 UTC, vzarytovskii approved these changes

2022-09-27 08:51 UTC, vzarytovskii requested changes
Ok, I will create 17.5 today and retarget it for 17.5

2022-09-27 10:05 UTC, vzarytovskii approved these changes

2022-09-27 10:05 UTC, merged