Introducing FSharp.Editor.Tests
dotnet/fsharp pull request #14335
Opened 2022-11-16 15:45 UTC by psfinaki

A new clean project dedicated for unit testing FSharp.Editor:
- No Salsa
- No legacy depedencies
- No weird file linking

This also brings a few extra changes on top of the mere moving of the files:
- Turned on Fantomas hence formatting
- Removed a bunch of unused code
- Set proper namespaces in all files
- Added MS copywrites in all files

What's beyond the scope:
- Further cleanup of VisualFSharp.UnitTests (there is a lot of cleanup potential there)
- Changing NUnit to xUnit
- Consolidating `type XTests` vs `module YTests` in suites

2022-11-16 18:21 UTC, KevinRansom approved these changes

2022-11-17 05:24 UTC, TIHan commented
My goodness, this is great.

2022-11-17 08:18 UTC, KevinRansom approved these changes

2022-11-17 15:19 UTC, vzarytovskii requested changes
Please, add the new test project to build scripts, under the corresponding switches, and make sure they show up in CI

2022-11-18 08:43 UTC, T-Gro approved these changes

2022-11-18 16:55 UTC, psfinaki commented
> Please, add the new test project to build scripts, under the corresponding switches, and make sure they show up in CI

Yep, all done, tests are running in CI:
![image](https://user-images.githubusercontent.com/5451366/202759312-d48675c4-d508-4e23-b735-3844fe3bbf8e.png)

2022-11-18 17:02 UTC, vzarytovskii approved these changes

2022-11-21 09:23 UTC, T-Gro approved these changes

2022-11-21 09:23 UTC, merged