Bind of Async<> within task{} should start on the same thread
dotnet/fsharp pull request #14499
Opened 2022-12-20 16:07 UTC by T-Gro

This addresses https://github.com/dotnet/fsharp/issues/14490 .

I am now of the opinion of the current behavior being a bug, and this change should be treated like a bugfix.

None of the docs for task{} and async{} mention starting work on a new thread, this operation is considered to be done explicitly by user code instead.

The proposed change for 'async{} inside task{}'  is also consistent with 'async in async' situation, causing less surprises when moving between task{} and async{}.

When it comes to backwards compatibility issues, GUI/main thread involvement is one thing to have in mind.
In the actual behavior's, the code could start on main thread, do the inner async{} elsewhere, and then return.
The proposed change will keep the same context, which I again see as a bugfix - both for correctness sake, but especially for resource utilization.

2022-12-20 16:39 UTC, psfinaki approved these changes

2022-12-20 16:50 UTC, vzarytovskii commented
Please, bump `FSharp.Core` version, since it's a change in behaviour.
@KevinRansom wdyt - is minor version bump enought?

2022-12-21 10:30 UTC, T-Gro commented on eng/Versions.props
> +    <FSMinorVersion>1</FSMinorVersion>
@vzarytovskii , @KevinRansom  : Like this?
Or did I oversee some other place(s), where I should make a change as well?

2022-12-21 11:53 UTC, vzarytovskii commented
To be completely fair, I'm still unsure if it was not a desired behaviour (starting on a thread pool), since this is a default for tasks in general.
@dsyme was it a deliberate choice?

2022-12-21 11:53 UTC, vzarytovskii requested changes
To be completely fair, I'm still unsure if it was not a desired behaviour (starting on a thread pool), since this is the expectation for tasks in general.

@dsyme was it a deliberate choice?

2022-12-21 12:16 UTC, T-Gro commented
> To be completely fair, I'm still unsure if it was not a desired behaviour (starting on a thread pool).
> 
> @dsyme was it a deliberate choice?

For full completeness and why I believe this should be treated like a bug/inconsistency:


**async inside Task:** Outer task before: 1, **inner async: 8, after inner async: 8**, outside of the CE: 1
**Task inside Task**: Outer task before: 1, inner task: 1, after inner task: 1, outside of the CE: 1
**async inside async**: Outer async before: 1, inner async: 1, after inner async: 1, outside of the CE: 1
**Task inside async:** Outer async before: 1, inner task: 1, after inner task: 1, outside of the CE: 1

Code:
```
open System.Threading

let getId() = Thread.CurrentThread.ManagedThreadId

let innerAsync() = async { return getId()  }
let innerTask() = task { return getId()  }

let asyncInTask() =
    let t = task {
        let a = Thread.CurrentThread.ManagedThreadId
        let! b = innerAsync()
        let c = Thread.CurrentThread.ManagedThreadId
        return $"Outer task before: {a}, inner async: {b}, after inner async: {c}"
    }
    let d = Thread.CurrentThread.ManagedThreadId
    $"Async inside Task: {t.Result}, outside of the CE: {d}"

let taskInTask() =
    let t = task {
        let a = Thread.CurrentThread.ManagedThreadId
        let! b = innerTask()
        let c = Thread.CurrentThread.ManagedThreadId
        return $"Outer task before: {a}, inner task: {b}, after inner task: {c}"
    }
    let d = Thread.CurrentThread.ManagedThreadId
    $"Task inside Task: {t.Result}, outside of the CE: {d}"

let asyncInAsync() =
    let t = async {
        let a = Thread.CurrentThread.ManagedThreadId
        let! b = innerAsync()
        let c = Thread.CurrentThread.ManagedThreadId
        return $"Outer async before: {a}, inner async: {b}, after inner async: {c}"
    }
    let d = Thread.CurrentThread.ManagedThreadId
    $"Async inside async: {(t |> Async.StartImmediateAsTask).Result}, outside of the CE: {d}"

let taskInsideAsync() =
    let t = async {
        let a = Thread.CurrentThread.ManagedThreadId
        let! b = innerTask() |> Async.AwaitTask
        let c = Thread.CurrentThread.ManagedThreadId
        return $"Outer async before: {a}, inner task: {b}, after inner task: {c}"
    }
    let d = Thread.CurrentThread.ManagedThreadId
    $"Task inside async: {t |> Async.RunSynchronously}, outside of the CE: {d}"

printfn "%s" (asyncInTask())
printfn "%s" (taskInTask())
printfn "%s" (asyncInAsync())
printfn "%s" (taskInsideAsync())
```

2022-12-22 02:09 UTC, abelbraaksma commented
@T-Gro that’s  an excellent summary. I agree, this looks like a minor oversight and should be fixed (I assume we won’t publish fixes on the 6.0.x branch anymore, right? This’ll be just 7.0.x? As that’d be an even greater reason in my book to not wait until 8.x).

Do note that similar wrong behaviour exists for running an async computation and hopping to a different thread immediately  (as opposed to when nested), see original issue for details.

2022-12-22 09:58 UTC, T-Gro commented on eng/Versions.props
> +    <FSMinorVersion>1</FSMinorVersion>
@KevinRansom told me that in the case of waiting for next preview version, we should leave the versioning scheme as is, it will cover for this.

2022-12-22 09:59 UTC, T-Gro commented on eng/Versions.props
> +    <FSMinorVersion>1</FSMinorVersion>
```suggestion
    <FSMinorVersion>0</FSMinorVersion>
```

2022-12-22 10:34 UTC, vzarytovskii approved these changes
As discussed offline, since it's an implementation detail change - not really explicitly breaking.
I'm just wondering what's what the thinking behind having current behaviour in the first place. Will discuss with Don in NY.

2022-12-27 13:42 UTC, 0101 approved these changes

2022-12-27 17:29 UTC, merged

2022-12-28 13:07 UTC, abelbraaksma commented
To answer my own question, and for posterity, this fix will only live in the F# Core 7.x.x versions published after today, there will not be a new 6.0.x (afaik).

2022-12-29 19:59 UTC, T-Gro commented
> To answer my own question, and for posterity, this fix will only live in the F# Core 7.x.x versions published after today, there will not be a new 6.0.x (afaik).

Sorry for the radio silence -> yes, this is the plan.

I do not see this as a 'showstopper' kind of bug that should be backported, even though we technically can if this causes enough pain.

2023-01-03 16:16 UTC, dsyme commented
I agree with the fix :) Nice job