Update docs.microsoft.com to learn.microsoft.com.
dotnet/fsharp pull request #14774
Opened 2023-02-21 07:13 UTC by nojaf

In light of https://github.com/fsprojects/FSharp.Formatting/issues/794, I want to update all documentation links from `https://docs.microsoft.com/` to `https://learn.microsoft.com/`.

2023-02-21 13:10 UTC, edgarfgp approved these changes

2023-02-21 14:19 UTC, abonie commented on src/FSharp.Core/async.fsi
> +    ///  See also <a href="https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/asynchronous-workflows">F# Language Guide - Async Workflows</a>.
This link (which appears in few other places in this file) does not work for me. Not quite sure what should be the correct one, but I am guessing this one: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/async-expressions

2023-02-21 20:24 UTC, KevinRansom requested changes
This looks good, however, per @baronfels request.
I believe if you remove the en-us from the urls, then it will go to localized versions of the documention depending on the browsers configuration.

E.g:
https://learn.microsoft.com/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#job

On my browser goes to: https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#job

So it would probably be preferable if we didn't make everyone read the us version of the docs.

2023-02-22 07:22 UTC, KevinRansom approved these changes
thanks

Kevin

2023-02-22 08:27 UTC, merged