Small optimization for DateTime comparison
dotnet/fsharp pull request #16587
Opened 2024-01-25 13:56 UTC by psfinaki

This is basically a followup to [this one](https://github.com/dotnet/fsharp/issues/8447). The DateTime comparisons were added [later](https://github.com/dotnet/fsharp/pull/9224/files) in the old fashion.

`DateTime.op_Equality` is [faster](https://sharplab.io/#v2:EYLgHgbALANANiAZgZxgFxAQ2QWwD4D2ADgKYB2ABAMoCeyaJOAsAFDHnUAWmATkQDKZgAOgBKAVzJoAljhKsFLVmhqkKAYQAUASgoBeVhSMUA2gB4AUtLQBxciR7SAxppWkCiMwBFMDACqyJAB82kEAuobG9L7OFHI4wA7UcAQA7mYA5H5BOvoUkcbGOL5OnBRuJB6Z2RSp1mUFhRR45TS1nBwqwgCiAI7imHDIrqqVnj7+gSEUALRBFACMjYUtAPqz8wBMy8aN5la29o4uFVUTJAFyIeGN0TJOcYyJPBQAYtho1Tm6evksTUUSmVTp4svM6mgGv8Ac1yu0OH5RsJiKs+gM4NYaK4YK13ONfBcpro5osdkY1hsKNtoQCyX8YfSYawgA) than `DateTime.Equals` on older platforms.
![image](https://github.com/dotnet/fsharp/assets/5451366/ed578883-ff17-47fe-bd7f-eae0921be769)

2024-01-25 14:25 UTC, T-Gro approved these changes

2024-01-29 16:34 UTC, vzarytovskii commented
I'm confused - code change is about changing equality of the `DateTime`, but ASM is showing equality for `Type`.

2024-01-29 16:39 UTC, vzarytovskii requested changes
I'm confused - code change is about equality of the `DateTime`, but example is showing equality for `Type`.

If we are to compare `DateTime`'s `Equals` vs `op_Equality`, then it would be something like

```fsharp
type C() =
    static member Slow(dt1: DateTime, dt2: DateTime) = dt1.Equals(dt2)
    static member Fast(dt1: DateTime, dt2: DateTime) = DateTime.op_Equality(dt1, dt2)
```

Which will roughly result in
```asm
_+C.Slow(System.DateTime, System.DateTime)
    L0000: mov rax, 0x3fffffffffffffff
    L000a: and rax, rcx
    L000d: mov rcx, 0x3fffffffffffffff
    L0017: and rdx, rcx
    L001a: cmp rax, rdx
    L001d: setz al
    L0020: movzx eax, al
    L0023: ret

_+C.Fast(System.DateTime, System.DateTime)
    L0000: mov rax, 0x3fffffffffffffff
    L000a: and rax, rcx
    L000d: mov rcx, 0x3fffffffffffffff
    L0017: and rdx, rcx
    L001a: cmp rax, rdx
    L001d: setz al
    L0020: movzx eax, al
    L0023: ret
```

of the full framework and

```asm
_+C.Slow(System.DateTime, System.DateTime)
    L0000: xor rcx, rdx
    L0003: shl rcx, 2
    L0007: sete al
    L000a: movzx eax, al
    L000d: ret

_+C.Fast(System.DateTime, System.DateTime)
    L0000: xor rcx, rdx
    L0003: shl rcx, 2
    L0007: sete al
    L000a: movzx eax, al
    L000d: ret
```

On the coreclr.

I don't see any difference here, are there any specific benchmarks for both?

If we want to change equality for **System.Type**, we likely can't do it as easy, like we do with any other types, since `Type` is abstract.

2024-01-29 16:42 UTC, vzarytovskii commented
If we want to change equality for **System.Type**, we likely can't do it easily, since `Type` is abstract.

2024-01-29 16:55 UTC, psfinaki commented
@vzarytovskii I used the technique described [here](https://github.com/dotnet/fsharp/issues/8447) and similar decompilation example - AFAIU (I might be wrong) this applies to the older runtimes whereas now RyuJIT is smarter.

2024-01-29 16:56 UTC, vzarytovskii commented
> @vzarytovskii I used the technique described [here](https://github.com/dotnet/fsharp/issues/8447) and similar decompilation example - AFAIU (I might be wrong) this applies to the older runtimes whereas now RyuJIT is smarter.

You make an optimisation for `DateTime`, but in SharpLab, it's `Type`, if you rewrite example to `DateTime`, you will see there's no difference in ASM, whether it's .NET Framework CLR or CoreCLR.

2024-01-29 17:10 UTC, psfinaki commented
Oh I see. Okay looks like I got confused here, I will close this.

2024-01-29 17:10 UTC, closed without merging