The benchmark leg seems to reliably fail
dotnet/fsharp pull request #16600
Opened 2024-01-27 10:23 UTC by KevinRansom

Investigate

2024-01-27 21:15 UTC, abonie approved these changes

2024-01-29 11:50 UTC, vzarytovskii requested changes

2024-01-29 11:50 UTC, vzarytovskii commented on eng/Build.ps1
> +        $properties += "/p:RuntimeIdentifier=win-x64"
We shouldn't have rid here, since it won't be runnable on Mac and Linux then.

2024-01-29 13:31 UTC, T-Gro approved these changes

2024-01-29 13:31 UTC, merged