Fix MEF issues with options
dotnet/fsharp pull request #17015
Opened 2024-04-10 13:21 UTC by vzarytovskii

Fixes #16965
It seems something changed about MEF import w.r.t. private members. @KevinRansom are we building VSIX with real signatures now by any chance?

Will appreciate confirmation whether it fixes the issue or not.

2024-04-10 13:30 UTC, vzarytovskii commented
Nvm, it doesn't fix it, it was coincidence. It seems like we import it before we export.

2024-04-10 16:33 UTC, majocha commented
I can confirm this fixes it. Nice!

2024-04-10 16:41 UTC, vzarytovskii commented
Well, that confuses me even more. It's either default MEF behaviour has changed, or we use realsig in the VSIX.

2024-04-10 17:09 UTC, T-Gro approved these changes

2024-04-10 17:10 UTC, T-Gro commented
Tested a few times.

Settings window was crashing for me.
On this PR, it never does.

2024-04-10 17:57 UTC, KevinRansom requested changes

2024-04-10 17:57 UTC, KevinRansom commented on vsintegration/src/FSharp.Editor/Options/EditorOptions.fs
> +    member _.SettingsStore = store
```suggestion
    member internal _.SettingsStore = store
```

2024-04-10 18:02 UTC, vzarytovskii commented
Might be mix of realsig + optimizer, since it's 
A. Doesn't fail while debugging vsix
B. Is exported via private property which isn't used anywhere. 

Might be, due to new codegen, optimized away in release build.

2024-04-10 18:04 UTC, vzarytovskii commented on vsintegration/src/FSharp.Editor/Options/EditorOptions.fs
> +    member _.SettingsStore = store
Will test it tomorrow if it still works

2024-04-11 10:53 UTC, merged

2024-04-11 10:53 UTC, vzarytovskii commented
/backport to release/dev17.10