Fix UseLocalCompiler.Directory.Build.props to invoke dotnet.exe
dotnet/fsharp pull request #17542
Opened 2024-08-15 11:40 UTC by T-Gro

Before, the setup was yielding:
![image](https://github.com/user-attachments/assets/ce2e9418-6b11-4e98-8d84-79c4bb03c020)
![image](https://github.com/user-attachments/assets/f5c3730b-8536-4988-9ff9-39e01b7e7c6e)

This makes sure that compilation happens by: dotnet.exe $pathToLocalFsc.dll

2024-08-15 13:05 UTC, Martin521 approved these changes
Thanks! I was just struggling with this.
The same should be added in FSharp.Compiler.Service.fsproj after line 60, because else the same error still occurs for dotnet build of that project.
(Or in Directory.Build.props?)

2024-08-15 13:15 UTC, vzarytovskii requested changes
That doesn't look correct. What are the exact circumstances it's happening under?

2024-08-15 13:17 UTC, T-Gro commented
> That doesn't look correct. What are the exact circumstances it's happening under?

Exact circumstances when I was testing in:
Copy over the original version of the file to a new folder ;; rename it to Directory.Build.props, set compiler path.
And then just plain `dotnet new ..` ;; it was failing.


This change is needed so that the invocation goes as "dotnet.exe ../fsc.dll"

2024-08-15 13:21 UTC, vzarytovskii commented
> > That doesn't look correct. What are the exact circumstances it's happening under?
> 
> 
> 
> Exact circumstances when I was testing in:
> 
> Copy over the original version of the file to a new folder ;; rename it to Directory.Build.props, set compiler path.
> 
> And then just plain `dotnet new ..` ;; it was failing.
> 
> 
> 
> 
> 
> This change is needed so that the invocation goes as "dotnet.exe ../fsc.dll"

That shouldn't be happening. It means that build task confuses the fact that it's running under corehost

2024-08-15 13:22 UTC, T-Gro commented
> > > That doesn't look correct. What are the exact circumstances it's happening under?
> > 
> > 
> > Exact circumstances when I was testing in:
> > Copy over the original version of the file to a new folder ;; rename it to Directory.Build.props, set compiler path.
> > And then just plain `dotnet new ..` ;; it was failing.
> > This change is needed so that the invocation goes as "dotnet.exe ../fsc.dll"
> 
> That shouldn't be happening. It means that build task confuses the fact that it's running under corehost

I think it did that because some essential settings get skipped when you DisableAutoSetFscCompilerPath, there is block of props.
Setting the dotnet path and file are two of them.

2024-08-15 13:24 UTC, Martin521 commented
Interesting. After adding these two lines in FSharp.Compiler.Service.fsprop, I *sometimes* get the `unrecognized option  /checknulls` errors and sometimes not. Haven't found out why.

2024-08-15 13:25 UTC, T-Gro commented
> Interesting. After adding these two lines in FSharp.Compiler.Service.fsprop, I _sometimes_ get the `unrecognized option /checknulls` errors and sometimes not. Haven't found out why.

Without your /artifacts contents changing? (i.e. not doing rebuilds in between, either CLI or from VS?)

2024-08-15 13:28 UTC, Martin521 commented
I do `git clean -xdf & dotnet build FSharp.Compiler.Service`

2024-08-15 13:59 UTC, Martin521 commented
> Without your /artifacts contents changing? (i.e. not doing rebuilds in between, either CLI or from VS?)

Possibly Ionide doing a build?

2024-08-15 14:57 UTC, vzarytovskii commented
I can't reproduce it in my machine no matter what I do :|

2024-08-15 15:01 UTC, Martin521 commented
Right now it`s working, let me observe if I can find something more specific.

2024-08-28 13:23 UTC, T-Gro commented
@Martin521 : Did it get better with the changes proposed here?
If yes, can I merge this change to be the new suggested template for using locally built compiler?

2024-08-28 19:46 UTC, Martin521 commented
> @Martin521 : Did it get better with the changes proposed here?

I haven't seen the issue that I mentioned any more, and it was not really related to the file you changed, just similar symptoms.
So, I am not sure if I can give any advice here.

I can create a new project in my environment tomorrow and test it with and without your changes, if that is helpful.

2024-08-29 09:19 UTC, merged

2024-08-30 10:06 UTC, T-Gro commented
Thanks @Martin521  for testing and verifying, this definitely helps