Remove redundant "ok" files in core tests
dotnet/fsharp pull request #17709
Opened 2024-09-12 14:51 UTC by psfinaki

This is to help @majocha in his journey for test parallelization [here](#17662).

We noticed these ubiquitous "test.ok" files creation in the tests. Most of them are in the tests/fsharp (core tests) - and this is the target of this PR.

Usually the files are created just before sending "exit 0" signal from tests. After this, they are sometimes checked (sometimes not). Now, there is no need for this really, because the test engine would fail the test if the exit code is different anyway. 

At the same time, files contaminate the logs and the file system which turns out to be one of the biggest obstacles for proper test parallelization.

Take this example, [quotesInMultipleModules](https://github.com/dotnet/fsharp/blob/main/tests/fsharp/core/quotesInMultipleModules/module2.fsx) tests. They do some tests and then print this "ok file". Now, let's remove the "ok file" and break the very first assertion:
```fsharp
let a = Module1.Test.bar()
let b = sprintf "%A" (Module1.Test.run())

let test1 = (a=b)
``` 
so that it's 
```
let test1 = (a <> b)
```

The tests fails:

![image](https://github.com/user-attachments/assets/0d259a79-15fc-44d3-aaa1-a3e151df363e)

I tested a few more cases just for sanity checks, but anyway the files are just the artifacts of ancient ways of testing we had here.

2024-09-12 15:11 UTC, majocha commented
Looking here:
https://github.com/dotnet/fsharp/blob/main/tests/FSharp.Test.Utilities/ScriptingShims.fsx

We may be losing some information without the file. It seems it was the only positive signal that the test script didn't fail silently.
At the moment we convert the exit 1 into exn throw, but we don't translate exit 0 to anything that can be captured as a positive signal of success. OTOH that's how testing works. We test for failures not for successes
.

2024-09-12 15:43 UTC, psfinaki commented
So what we need is to understand where the problem is if it happens. For that matter, these files don't help really, whereas the test framework propagates exceptions to the tests outputs anyway. Sometimes it looks ugly, but then it's up to the specific test to improve the situation a bit.

In the example above, nothing really changes if the "test.ok" files is being created - the log is still the same. There might be some edge cases where the "test.ok" is handled in some special manner, but I didn't notice anything interesting in that regard and that can be handled later if needed... But if you notice any particular information we might be missing, then yes, it's worth finding a way to compensate it.

2024-09-12 16:23 UTC, majocha commented
I think that shim is just for stuff executed in hosted fsi. We also run some suff out of proc. It's something to investigate.
Anyway this change is for the better. We can add a better signaling mechanism than creating a "ok" file, if needed.

2024-09-12 17:26 UTC, psfinaki commented
Alright so this seems to work, tests seem to be running as they used to.

Don't know how much time this saves for the CI since the CI times vary a lot anyway - we'll see.

2024-09-12 17:28 UTC, psfinaki commented
@KevinRansom maybe run your eyes over this one, if any concerns come to your mind :)

2024-09-16 18:59 UTC, KevinRansom approved these changes
Sweet, I will be glad to see the back of these.

2024-09-17 08:15 UTC, T-Gro requested changes
With any change like this, it is not the goal to see that "tests still pass". Rather the opposite, it is important that they can still fail :-).

What measures have been taken for all types of tests affected by this change to make sure they can still fail?
(in-proc tests, out of proc tests, tests using the `exec cfg ...` primitives in a longer series...)


Was the change generated with a regex/script that guaranteed the opposite clause/branch to always yield an `exit 1`, and then verified it always leads to test failure in all forms of test execution, not just a few selected ones ?  E.g. for topinit/generate.fsx it is not immediately obvious. Has it been tested it can still fail properly?



Most importantly, the tests are executed in multiple forms, and we should see evidence that each of these forms still fails the test run in an equivalent way.
In the in-process migrated FSharpSuite, this will be mainly a single place to verify - that one would be fine to demonstrate with just a few examples of failure (exit code, exception, runtime never getting to the block of code writing the file,...). 

In the out-of-proc Fsharp.Suite, there are more ways on how the tests are run via the DSL (such as FSI_NETFX_STDIN , FSC_NETFX_TEST_ROUNDTRIP_AS_DLL,..) as well as via custom primitives for checking the file in sequential code.
Typeprovider tests come to mind as an example, as they can have multiple causes of failure, and each of the causes should still lead to a visible test failure after this change.

2024-09-18 15:33 UTC, psfinaki commented
@T-Gro thanks for the considerations.

In general:
- I did some "smoke testing" in that regard, deliberating bugging some tests and seeing them failing
- @majocha is battletesting the whole testing infra in #17662 where he incorporated these changes as well, tests behave as expected there as well

---

> What measures have been taken for all types of tests affected by this change to make sure they can still fail?
(in-proc tests, out of proc tests, tests using the exec cfg ... primitives in a longer series...)

So the tests here are coming from different backgrounds. To get some diversity, let's look at different tests in `tests.fs`.

Most common type of test in when things are just being compiled and run, like in the case of `subtype-langversion-checknulls`:
```fsharp
    [<Fact>]
    let ``subtype-langversion-checknulls`` () =
        let cfg = testConfig "core/subtype"
        fsc cfg "%s -o:test-checknulls.exe -g --checknulls" cfg.fsc_flags ["test.fsx"]
        exec cfg ("." ++ "test-checknulls.exe") ""
```

Let's set the `core/subtype/test.fsx` to not compile - put "blah" at the end. We are getting the failed test as expected:

![image](https://github.com/user-attachments/assets/947f39d0-bef8-43ae-87f4-e95e04dab5c8)

Let's put a runtime error then -  change `test "cenwceoiwe1" ((id |> toConverter |> fromConverter) 6 = 6)` to equal 5. This also still fails:

![image](https://github.com/user-attachments/assets/fe05fc72-09f9-4b12-99c4-2f5e92106221)

We can still achieve the same just running the target file in fsi: `fsi core/subtype/test.fsx`:

![image](https://github.com/user-attachments/assets/58084583-e1eb-42a7-a066-514dbc0df492)

---

Then there are these `SDKTests`, those are trying to build some projects and run targets on them:
```fsharp
    [<Fact>]
    let ``SDKTests`` () =
        let cfg = testConfig "SDKTests"

        let FSharpRepositoryPath = Path.GetFullPath(__SOURCE_DIRECTORY__ ++ ".." ++ "..")

        let projectFile = cfg.Directory ++ "AllSdkTargetsTests.proj"

        exec cfg cfg.DotNetExe ($"msbuild {projectFile} /p:Configuration={cfg.BUILD_CONFIG} -property:FSharpRepositoryPath={FSharpRepositoryPath}")
```

To fail then, we can bug the project file:

![image](https://github.com/user-attachments/assets/58237b8f-b1b8-4577-84b6-256b46431856)

---

Then there are these `singleTestBuildAndRun` tests:
```fsharp
    [<Fact>]
    let ``attributes-FSC_OPTIMIZED`` () = singleTestBuildAndRun "core/attributes" FSC_OPTIMIZED
```

Those are similar to the first category, let me remove the `Inline` in this line there:
```
    check "vwlnwer-0wreknj3" (test2()) "Equals: [||], ExtensionMethod: [||], GetHashCode: [||], GetType: [||], ToString: [||], get_Item: [|Inline|], get_P: [||], set_Item: [|Inline|]"
```

Those also still fail:
![image](https://github.com/user-attachments/assets/9bbc9642-cd39-4df4-ae8f-c2748c45810e)

---

Then there are some negative baseline tests:
```fsharp
    [<Fact>]
    let ``state-machines neg-resumable-01`` () =
        let cfg = testConfig "core/state-machines"
        singleVersionedNegTest cfg "preview" "neg-resumable-01"
```

It's enough to put an extra empty line in the target file to get a mismatch between warning ranges:

![image](https://github.com/user-attachments/assets/30aa11f6-8b9a-4844-b867-fc658493f762)

---

Yet others are calling other fun stuff like `fsi` or `csc`:

```
    [<Fact>]
    let events () =
        let cfg = testConfig "core/events"
        fsc cfg "%s -a -o:test.dll -g" cfg.fsc_flags ["test.fs"]
        peverify cfg "test.dll"
        csc cfg """/r:"%s" /reference:test.dll /debug+""" cfg.FSCOREDLLPATH ["testcs.cs"]
        peverify cfg "testcs.exe"
        fsi cfg "" ["test.fs"]
        exec cfg ("." ++ "testcs.exe") ""
```

If I mess up with C# code, I still get the exception propagated through the test failure:

![image](https://github.com/user-attachments/assets/4fded1a2-9135-41d7-bc08-96cccf06f994)

---

> Was the change generated with a regex/script that guaranteed the opposite clause/branch to always yield an exit 1, and then verified it always leads to test failure in all forms of test execution, not just a few selected ones ? E.g. for topinit/generate.fsx it is not immediately obvious. Has it been tested it can still fail properly?

Exit code were already mostly there, there were just a few places missing them, I put exit codes there manually. The topinit tests are a bit beyond my comprehension but at least if I mess up with a file mentioned there, I get errors.

> Typeprovider tests come to mind as an example, as they can have multiple causes of failure, and each of the causes should still lead to a visible test failure after this change.

Same here, I messed up with some target files and still seem to get errors:

![image](https://github.com/user-attachments/assets/90935d2b-6076-4d15-82df-6272f4e3702c)

---

As I say, the tests have different backgrounds here and it's not always obvious how they are supposed to pass and fail, but above is at least some evidence. Importantly, there are these bad exit codes set up everywhere so it's reasonable to expect that tests fail via natural xUnit means.

2024-09-18 16:57 UTC, majocha commented
Conceptually, the testok file was _the_ signal of test success. An exe or a script can always return 0 because it just finished it's run one way or another but it does not necessarily mean it tested what it intended to test and determined it to be ok. We had such situations reported as failures before, "script returned 0 but test ok not created" or something like this.

2024-09-18 18:42 UTC, majocha commented
The challenge here is to find a channel of communication other than the filesystem, that would be as ubiquitous an work across the whole zoo of different modes of execution that we have for these tests.

2024-09-19 07:31 UTC, T-Gro commented
For the in memory ones, it gets easier - we can pass in a shim for FileSystem API and it could store the result in a mutable, and the test engine then verify.

But for those FSC/FSI/FSC_DLL_ROUNDTRIP as well as manual .exe invocations, in-memory shim would not communicate it back.

I actually do want to change Fsharp.Suite (slowest CI suite) to run on multiple agents (so not multithreading. Not even multi-processing. But multiple machines). Manually running the full suite from VS would still be single threaded and slow, but at least CI times would not suffer.


And if your journey to enable multithreaded parallelization could focus just on componenttests suite for example (at least for me, this is the suite I run locally most of the time), maybe the ROI would improve significantly?

2024-09-19 08:54 UTC, majocha commented
>Fsharp.Suite (slowest CI suite) 
@T-Gro, in my experiment I think the slowest one is actually ComponentTests, both in terms of physical running time and cumulative CPU time (?)

Desktop FSharpSuite with no limit on multithreading I can run in 6 - 7 minutes:
![image](https://github.com/user-attachments/assets/5cc6e37e-b3be-44b1-80ec-cad19503e8cf)

ComponentTests with same settings around 13 minutes:
![image](https://github.com/user-attachments/assets/4b88383f-2b49-4ef8-8da9-4e68b0bdb281)

2024-09-19 09:01 UTC, psfinaki commented
@T-Gro so far the investment has been quite small - I've created the regex, added a few exit codes and went through the tests which was useful for getting a picture.

I am reluctant to dig deep into all the aspects that you mention, especially with different types of testing - we don't have this documented properly, we don't know who and how uses it, so basically - I am not entirely sure how to do that and this would be a much bigger mental and time investment.

So maybe @majocha we take a different strategy - instead of removing all the ok files, maybe you can come up with the particular tests that come into your way in your parallelization efforts? Then we can adjust only those, and it will be easier to reason about.

2024-09-19 09:22 UTC, majocha commented
ATM I'm experimenting with an idea:

Since I already have stdout abstracted per test case in my experiment, I can use it instead of the filesystem. Just do printfn "TEST PASSED OK" and then check the captured stdout.

This is quite general and works for me in all of the cases but one, that is really black magic: 

Here fsi is being executed as part of a build, I believe with the target
`<UsingTask TaskName="Fsi" AssemblyFile="$(FSharpBuildAssemblyFile)" />`
https://github.com/dotnet/fsharp/blob/767b5ecfc3ea740f41a833a180e6443c5ed2dbc4/tests/fsharp/single-test.fs#L302
Is there a way to spit out Fsi output along with the rest of the build output?
@KevinRansom, you probably know the most about it, is it possible?

2024-09-19 15:07 UTC, majocha commented
This is now dealt with in my PR, the way I described above, not elegantly but should work.

2024-09-19 15:44 UTC, psfinaki commented
Alright then, thanks Jakub, I'll close this one :)

2024-09-19 15:44 UTC, closed without merging