Fix `fsi` auto-loading of script file inside NuGet package.
dotnet/fsharp pull request #18177
Opened 2024-12-25 01:36 UTC by teo-tsirpanis

## Description

In the project file generated by `FSharp.DependencyManager.NuGet`, we've been referencing a `PackageRoot` item metadata that does not exist (line 136), causing inability to find the script file, 

Fixes #18176 as validated locally by patching the `FSharp.DependencyManager.Nuget.dll` of a .NET SDK installation.

## Checklist

- [ ] Test cases added
- [ ] Performance benchmarks added in case of performance changes
- [ ] Release notes entry updated:
    > Please make sure to add an entry with short succinct description of the change as well as link to this pull request to the respective release notes file, if applicable.
    >
    > Release notes files:
    > - If anything under `src/Compiler` has been changed, please make sure to make an entry in `docs/release-notes/.FSharp.Compiler.Service/<version>.md`, where `<version>` is usually "highest" one, e.g. `42.8.200`
    > - If language feature was added (i.e. `LanguageFeatures.fsi` was changed), please add it to `docs/release-notes/.Language/preview.md`
    > - If a change to `FSharp.Core` was made, please make sure to edit `docs/release-notes/.FSharp.Core/<version>.md` where version is "highest" one, e.g. `8.0.200`.

    > Information about the release notes entries format can be found in the [documentation](https://fsharp.github.io/fsharp-compiler-docs/release-notes/About.html).
    > Example:
    > * More inlines for Result module. ([PR #16106](https://github.com/dotnet/fsharp/pull/16106))
    > * Correctly handle assembly imports with public key token of 0 length. ([Issue #16359](https://github.com/dotnet/fsharp/issues/16359), [PR #16363](https://github.com/dotnet/fsharp/pull/16363))
    > *`while!` ([Language suggestion #1038](https://github.com/fsharp/fslang-suggestions/issues/1038), [PR #14238](https://github.com/dotnet/fsharp/pull/14238))

    > **If you believe that release notes are not necessary for this PR, please add `NO_RELEASE_NOTES` label to the pull request.**

2024-12-25 01:43 UTC, baronfel approved these changes
This MSBuild-fu is good.

2025-01-02 10:24 UTC, T-Gro commented
This is a good fix.

@teo-tsirpanis We do have some existing tests which use "nuget: .." dependency loading and validating some cases.

Do you have a package where the fixed behavior happens?
If yes, could this be added as a test?

2025-01-03 04:24 UTC, KevinRansom approved these changes
looks good.

2025-01-03 04:26 UTC, KevinRansom commented
I will take a look at the test failures.

2025-01-03 05:52 UTC, KevinRansom requested changes
The test failures are signficant.

2025-01-03 09:53 UTC, teo-tsirpanis commented
@KevinRansom CI is now green. @T-Gro I will make use of this for the next version of the [Farkle](https://github.com/teo-tsirpanis/Farkle) library, but it is not yet published. I don't know any other package that does this.

2025-01-06 10:44 UTC, T-Gro commented
> @KevinRansom CI is now green. @T-Gro I will make use of this for the next version of the [Farkle](https://github.com/teo-tsirpanis/Farkle) library, but it is not yet published. I don't know any other package that does this.

It would be great if there was at least 1 integration test, even for a preview/beta version of anything, demonstrating this does not crash and indeed loads the script.

Or perharps if the test first created a local package, changed nuget to look at local folder instead of public feed, and loaded it?

2025-01-13 13:00 UTC, T-Gro approved these changes

2025-01-13 17:35 UTC, KevinRansom approved these changes

2025-01-13 18:41 UTC, merged