Bugfix :: Nullness in signature file is not considered by implementation and vice versa
dotnet/fsharp pull request #18186
Opened 2024-12-30 14:27 UTC by T-Gro

Fixes # 18058 
Fixes # 18184
Fixes # 18185

2025-02-04 18:28 UTC, KevinRansom requested changes
@tomas, this looks good, but I have a small question on 
onlyDiffersInNullness generating a warning, which I hope you can clear up for me.  Other than it looks great

2025-02-04 18:28 UTC, KevinRansom commented on tests/FSharp.Compiler.ComponentTests/EmittedIL/Nullness/HasSignatureWithMissingOverride.fs.il.bsl
Empty baseline file?  I assume because the test fails to build, expected compile failures do not need il baselines I believe.

2025-02-04 18:28 UTC, KevinRansom commented on src/Compiler/Checking/MethodCalls.fs
> +            let n = mbase.PApplyArray((fun x -> x.GetParameters()),"GetParameters", m).Length
nameof for "GetParameters"?

````
> let x = typeof<int>;;
    nameof x.ToString;;
val it: string = "ToString"
````

2025-02-04 18:28 UTC, KevinRansom commented on src/Compiler/Checking/NicePrint.fs
> +                        for nestedType in info.ProvidedType.PApplyFilteredArray((fun sty -> sty.GetNestedTypes()),(fun t -> t.IsPublic || t.IsNestedPublic), "GetNestedTypes", m) do
perhaps moar nameof

2025-02-04 18:28 UTC, KevinRansom commented on src/Compiler/Checking/NicePrint.fs
> +            let assemblyName = PrintTypes.layoutAssemblyName denv t |> function | "" -> "" | name -> sprintf " (%s)" name
surely $" ({name})"

2025-02-04 18:28 UTC, KevinRansom commented on src/Compiler/Checking/NicePrint.fs
> +            let assemblyName = PrintTypes.layoutAssemblyName denv t |> function | "" -> "" | name -> sprintf " (%s)" name
bonus kudos for using function match :-)

2025-02-04 18:28 UTC, KevinRansom commented on src/Compiler/Checking/SignatureConformance.fs
> +                        if onlyDiffersInNullness then
Shouldn't the signature be at least as restrictive as the implementation.

E.g. If the implementation can produce null then if the signature says, never produces null, wouldn't that be a problem?

Although I could easily misunderstand the feature :-)

2025-02-04 18:34 UTC, T-Gro commented on src/Compiler/Checking/SignatureConformance.fs
> +                        if onlyDiffersInNullness then
The nullness difference can be on any level - argument, return type, generic parameter to either of them, domainTy vs retTy to a function argument.
It really then depends on the co- vs contra-variance of that argument which is a concept that I did not want to introduce just for this check.

That it's why it checks for equality.

2025-02-04 19:27 UTC, tomas commented
@KevinRansom please do not mention me again in this repo.

2025-02-04 22:25 UTC, KevinRansom commented on src/Compiler/Checking/SignatureConformance.fs
> +                        if onlyDiffersInNullness then
I think that may make sense.

2025-02-04 22:27 UTC, KevinRansom commented
> @KevinRansom please do not mention me again in this repo.

Well, there have been quite a few Tomas' that have worked on F# over the years.  I will do my best not to mention you, but you do have the coolest alias.

2025-02-04 22:28 UTC, KevinRansom approved these changes

2025-02-05 09:40 UTC, 0101 approved these changes

2025-02-05 09:40 UTC, 0101 commented on tests/FSharp.Test.Utilities/Compiler.fs
> +                    eprintfn "%s" errorMsg
Do we want to keep this here or was it just for debugging?

2025-02-05 09:40 UTC, 0101 commented on src/Compiler/Driver/ParseAndCheckInputs.fs
> +                    priorErrors || (logger.CheckForRealErrorsIgnoringWarnings)
Should we also make the same change for Sequential checking?

2025-02-06 10:41 UTC, T-Gro commented on src/Compiler/Checking/MethodCalls.fs
> +            let n = mbase.PApplyArray((fun x -> x.GetParameters()),"GetParameters", m).Length
No access to an instance to apply `nameof` to. mbase is a `tainted`, so cannot really reach it's symbols :(

2025-02-06 10:47 UTC, T-Gro commented on src/Compiler/Checking/NicePrint.fs
> +                        for nestedType in info.ProvidedType.PApplyFilteredArray((fun sty -> sty.GetNestedTypes()),(fun t -> t.IsPublic || t.IsNestedPublic), "GetNestedTypes", m) do
Also not reachable, since the type is `tainted` and I cannot reach it's symbols for members.

2025-02-06 12:02 UTC, merged